name: Deploy JobTracker App (.NET + Angular)

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change if your default branch is different

env:
  NODE_VERSION: '20'   # Angular requires Node 20 or higher
  DOTNET_VERSION: '8.0.x'   # Your .NET version
  AZURE_FRONTAPP_PACKAGE_PATH:  "./job-tracker-frontend/dist/job-tracker-frontend/browser"
  AZURE_BACKAPP_PACKAGE_PATH:  "./job-tracker-backend"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        
      # 1️⃣ Build Angular frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Angular dependencies
        working-directory: ./job-tracker-frontend
        run: npm install

      - name: Build Angular app
        working-directory: ./job-tracker-frontend
        run: npm run build -- --configuration production

      # -------------------------------
      # 2️⃣ Deploy Angular frontend to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        name: Deploy Angular frontend using Azure CLI
        with:
         app-name: ${{ secrets.AZURE_FRONTEND_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_FRONTEND }}
         package: ${{ env.AZURE_FRONTAPP_PACKAGE_PATH }}
         
      # -------------------------------
            # 3️⃣ Build .NET backend
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET dependencies
        working-directory: ./job-tracker-backend
        run: dotnet restore

      - name: Build .NET backend
        working-directory: ./job-tracker-backend
        run: dotnet build --configuration Release

      - name: Publish .NET backend
        working-directory: ./job-tracker-backend
        run: dotnet publish -c Release -o publish

      # -------------------------------
      # 4️⃣ Deploy .NET backend to Azure

      - uses: azure/webapps-deploy@v2
        name: Deploy .NET backend using Azure CLI
        with:
         app-name: ${{ secrets.AZURE_BACKEND_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_BACKEND }}
         package: '${{ env.AZURE_BACKAPP_PACKAGE_PATH }}/publish'
